#include <Arduino.h>

#define NEOPIXEL_ORDERING NeoGrbFeature

namespace Pins
{
    static const uint STATUS_LED = 0;
    static const uint NEOPIXEL = 16;
    // static const uint MAX_BRIGHTNESS_POT = A1; // Not used
    // static const uint MIN_BRIGHTNESS_POT = A0; // Not used
    static const uint LDR = A2;

    static const uint DIP_WIND = 5;
    static const uint DIP_LIGHTNING = 6;
    static const uint DIP_DIMMING = 7;
    static const uint DIP_WIFI_SETUP = 8;
}

namespace Features
{
    static const String MODEL = "AM-M00810NE-1";

    // Analog inputs
    static const bool LDR = true;

    // Defaults
    static const float DEFAULT_LDR = 1.0;         // 0-1
    static const uint8_t DEFAULT_BRIGHTNESS = 20; // 0-100

    // LED current draw (~12 mA per LED at full brightness):
    //   255 -> 710 mA
    //   128 -> 360 mA
    //   64  -> 160 mA
    //   32  -> 60 mA
    // (+100 mA for Pico)
    static const uint8_t MASTER_MIN_BRIGHTNESS = 2;  // 0-255
    static const uint8_t MASTER_MAX_BRIGHTNESS = 64; // 0-255
}

namespace Airports
{
    static const char *IDs[] = {
        "KPQI",
        "CYSL",
        "KCAR",
        "KFVE",
        "CYVO",
        "CYQB",
        "KHUL",
        "KMVM",
        "KPNN",
        "KLRG",
        "KMLT",
        "CYRQ",
        "CYMX",
        "CYUL",
        "CYHU",
        "CYSC",
        "KERR",
        "KOWK",
        "KWVL",
        "KBGR",
        "KBST",
        "KOLD",
        "KBHB",
        "KRKD",
        "KIWI",
        "KAUG",
        "KLEW",
        "KIZG",
        "KBML",
        "KHIE",
        "KCDA",
        "KEFK",
        "KMPV",
        "KMVL",
        "KBTV",
        "KFSO",
        "KPBG",
        "KMAL",
        "KMSS",
        "CYND",
        "CYOW",
        "CYGK",
        "KOGS",
        "KGTB",
        "KPTD",
        "KSLK",
        "KLKP",
        "KRUT",
        "KVSF",
        "KLEB",
        "KLCI",
        "KCON",
        "KDAW",
        "KFSM",
        "KPSM",
        "KPWM",
        "KPVC",
        "KGHG",
        "KBVY",
        "KBOS",
        "KOWD",
        "KLWM",
        "KBED",
        "KMHS",
        "KASH",
        "KFIT",
        "KORH",
        "KGDM",
        "KAFN",
        "KORE",
        "KEEN",
        "KAQW",
        "KDDH",
        "KALB",
        "KGFL",
        "KRME",
        "KART",
        "KFZY",
        "CYTR",
        "CYPQ",
        "CYOO",
        "CYSN",
        "KIAG",
        "KBUF",
        "KGVQ",
        "KROC",
        "KIUA",
        "KSDC",
        "KPEO",
        "KITH",
        "KSYR",
        "KVGC",
        "KOIC",
        "KPSF",
        "KGBR",
        "KBAF",
        "KBDL",
        "KHFD",
        "KIJD",
        "KSFZ",
        "KPVD",
        "KOQU",
        "KTAN",
        "KEWB",
        "KPYM",
        "KFMH",
        "KMVY",
        "KHYA",
        "KCQX",
        "KACK",
        "KBID",
        "KWST",
        "KMTP",
        "KGON",
        "KJPX",
        "KFOK",
        "KSNC",
        "KHWV",
        "KHVN",
        "KISP",
        "KMMK",
        "KBDR",
        "KOXC",
        "KDXR",
        "KHPN",
        "KPOU",
        "KSWF",
        "KFWN",
        "KMSV",
        "KBGM",
        "KELM",
        "KDSV",
        "KELZ",
        "KOLE",
        "KJHW",
        "KDKK",
        "KFKL",
        "KAXQ",
        "KDUJ",
        "KBFD",
        "KOYM",
        "KFIG",
        "KLHV",
        "KIPT",
        "KSEG",
        "KZER",
        "KHZL",
        "KAVP",
        "KMPO",
        "KABE",
        "KSMQ",
        "KMMU",
        "KEWR",
        "KTEB",
        "KLGA",
        "KBLM",
        "KJFK",
        "KFRG",
        "KNEL",
        "KACY",
        "KWRI",
        "KVAY",
        "KTTN",
        "KPNE",
        "KDYL",
        "KPHL",
        "KLOM",
        "KCKZ",
        "KILG",
        "KOQN",
        "KPTW",
        "KMQS",
        "KRDG",
        "KLNS",
        "KMUI",
        "KTHV",
        "KCXY",
        "KRVL",
        "KUNV",
        "KPSB",
        "KAOO",
        "KJST",
        "KIDI",
        "KBTP",
        "KPIT",
        "KPJC",
        "KAFJ",
        "KWAY",
        "KAGC",
        "KFWQ",
        "KMGW",
        "KVVS",
        "KLEB",
        "KCBE",
        "KHMZ",
        "KMRB",
        "KHGR",
        "KFDK",
        "KDMW",
        "KGAI",
        "KBWI",
        "KMTN",
        "KANP",
        "KAPG",
        "KEVY",
        "KDOV",
        "KGED",
        "KMIV",
        "KWWD",
        "KOXB",
        "KCGE",
        "KESN",
        "KADW",
        "KCGS",
        "KCDA",
        "KDAA",
        "KIAD",
        "KJYO",
        "KOKV",
        "KFRR",
        "KCKB",
    };

    static const int COUNT = sizeof(IDs) / sizeof(IDs[0]);
}