#ifndef AIRPORTS_H
#define AIRPORTS_H

#include <Arduino.h>

namespace Airports
{
    const String IDs[] = {
        "KSFM",
        "KDAW",
        "KCON",
        "KVSF",
        "KRUT",
        "KGFL",
        "KRME",
        "KFZY",
        "KSYR",
        "KVGC",
        "KOIC",
        "NY0",
        "KSCH",
        "5B2",
        "KALB",
        "KAQW",
        "KEEN",
        "KORE",
        "KFIT",
        "KASH",
        "KMHT",
        "KLWM",
        "KBVY",
        "KPYM",
        "KBOS",
        "KOWD",
        "KBED",
        "KSFZ",
        "KORH",
        "KCEF",
        "KBDL",
        "KBAF",
        "KPSF",
        "1B1",
        "N66",
        "N23",
        "KBGM",
        "KMSV",
        "KMGJ",
        "KSWF",
        "KPOU",
        "KDXR",
        "KOXC",
        "KHFD",
        "KIJD",
        "KWST",
        "KPVD",
        "KOQU",
        "KEWB",
        "KMVY",
        "KHYA",
        "KACK",
        "KGON",
        "KFOK",
        "KHWV",
        "KHVN",
        "KISP",
        "KBDR",
        "KTEB",
        "KCDW",
        "KMMU",
        "KMPO",
        "KAVP",
        "KHZL",
        "KZER",
        "KRDG",
        "KABE",
        "KCKZ",
        "N51",
        "KLDJ",
        "KEWR",
        "KLGA",
        "KJFK",
        "KFRG",
    };

    const int COUNT = sizeof(IDs) / sizeof(IDs[0]);

    int findAirportIndex(String airportID);
}

#endif